# version: '3.8'

services:
  youtube-search-service:
    build:
      context: ./youtube-search-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - convert-video-service

  youtube-search-video-service:
    build:
      context: ./youtube-search-video-service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
  convert-video-service:
    build:
      context: ./convert-video-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ~/Downloads:/app/downloads
  music-player:
    build:
      context: ./music-player
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    depends_on:
      - convert-video-service
