# version: '3.8'

services:
  youtube-search-service:
    build:
      context: ./youtube-search-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      # - FLASK_APP=app.py
      - youtube-search-service/.env
    depends_on:
      - convert-video-service
  convert-video-service:
    build:
      context: ./convert-video-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ~/Downloads:/app/downloads
