# version: '3.8'

services:
  youtube-search-playlist-service:
    build:
      context: ./youtube-search-playlist-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - download-service

  youtube-search-video-service:
    build:
      context: ./youtube-search-video-service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
  download-service:
    build:
      context: ./download-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ~/Downloads:/app/downloads
  music-player:
    build:
      context: ./music-player
      dockerfile: Dockerfile
    ports:
      - "5004:5000"
    depends_on:
      - download-service
