---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpa
spec:
  selector:
    matchLabels:
      app: nginx-vpa
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-vpa
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
        - name: nginx
          image: nginx
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do timeout 0.5s yes >/dev/null; sleep 0.5s; done"
