apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert-deployment
  labels:
    app: music-player
  annotations:
    description: "This deployment is responsible for converting video files"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: music-player
  template:
    metadata:
      labels:
        app: music-player
    spec:
      containers:
      - name: convert-container
        image: convert:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: convert-service
  labels:
    app: music-player
  annotations:
    description: "This service is responsible for converting video files"
spec:
  selector:
    app: music-player
  type: ClusterIP
  ports: 
    - protocol: TCP
      port: 5000
      targetPort: 5000

