apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-player-deployment
  labels:
    app: music-player
  annotations:
    description: "This deployment is responsible for converting video files"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-player
  template:
    metadata:
      labels:
        app: music-player
    spec:
      containers:
      - name: music-player-container
        image: music-player:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: music-player-service
  labels:
    app: music-player
spec:
  selector:
    app: music-player
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: play.music.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: music-player-service
                port:
                  number: 5000